; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = giga_r1_m7
src_dir = test/Line_Planting_IMU

[env:giga_r1_m7]
platform = ststm32
board = giga_r1_m7
framework = arduino
monitor_speed = 115200
lib_deps = 
	pololu/Motoron@^1.5.0
	kkloesener/MFRC522_I2C@^1.0
	sparkfun/SparkFun VL53L5CX Arduino Library@^1.0.3
	adafruit/Adafruit ICM20X@^2.0.7
	adafruit/Adafruit Unified Sensor@^1.1.15
	arduino-libraries/Arduino_Modulino@^0.8.0
	arduino-libraries/Servo@^1.3.0
	pololu/QTRSensors@^4.0.0
	alexandros-charitonidis/MiniMessenger@^1.0.0
	arduino-libraries/ArduinoMqttClient@^0.1.8
